name: himin-ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Set YML
      run: |
        mkdir -p src/main/resources
        echo "${{ secrets.DATABASE_PROPERTIES }}" | base64 --decode > src/main/resources/application.yml
        find src

    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'himin' 
        mysql user: 'test'
        mysql password: ${{ secrets.MYSQL_DB_SECRET }}
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
